
##https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml
# Empty listen_addresses to use systemd socket activation
## List of local addresses and ports to listen to. Can be IPv4 and/or IPv6.
## Example with both IPv4 and IPv6:
## listen_addresses = ['127.0.0.1:53', '[::1]:53']
##
## To listen to all IPv4 addresses, use listen_addresses = ['0.0.0.0:53']
## To listen to all IPv4+IPv6 addresses, use listen_addresses = ['[::]:53']
listen_addresses = ['127.0.0.10:54']
server_names = ['google','cloudflare']
dnscrypt_servers = true
doh_servers = true
ipv6_servers = false
ipv4_servers = true
require_dnssec = true

block_ipv6 = true

##############################
#  Exceçom para rede Abalar  #
##############################

forwarding_rules = '/etc/CTparental/dnscrypt-forwarding-rules.txt'

###############################
#        Cloaking rules       #
###############################
## Cloaking returns a predefined address for a specific name.
## In addition to acting as a HOSTS file, it can also return the IP address
## of a different name. It will also do CNAME flattening.
##
## Example map entries (one entry per line)
## example.com     10.1.1.1
## www.google.com  forcesafesearch.google.com

cloaking_rules = '/etc/CTparental/dnscrypt-cloaking-rules.txt'

###########################
#        DNS cache        #
###########################
## Enable a DNS cache to reduce latency and outgoing traffic
cache = true
## Cache size
cache_size = 4096
## Minimum TTL for cached entries
cache_min_ttl = 2400
## Maximum TTL for cached entries
cache_max_ttl = 86400
## Minimum TTL for negatively cached entries
cache_neg_min_ttl = 60
## Maximum TTL for negatively cached entries
cache_neg_max_ttl = 600

## Automatic log files rotation
# Maximum log files size in MB - Set to 0 for unlimited.
#log_files_max_size = 10
# How long to keep backup files, in days
#log_files_max_age = 7
# Maximum log files backups to keep (or 0 to keep all backups)
#log_files_max_backups = 1
[query_log]
#  file = '/var/log/CTdnscrypt-proxy/query.log'
  file = '/dev/null'

[nx_log]
#  file = '/var/log/CTdnscrypt-proxy/nx.log'
  file = '/dev/null'

[sources]
  [sources.'public-resolvers']
  url = 'http://192.168.200.1/public-resolvers/public-resolvers.md'
  cache_file = '/var/cache/CTdnscrypt-proxy/public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

######################################################
#        Pattern-based blocking (blocklists)         #
######################################################

## Blocklists are made of one pattern per line. Example of valid patterns:
##
##   example.com
##   =example.com
##   *sex*
##   ads.*
##   ads*.example.*
##   ads*.example[0-9]*.com
##
## Example blocklist files can be found at https://download.dnscrypt.info/blocklists/
## A script to build blocklists from public feeds can be found in the
## 
[blocked_names]
## Path to the file of blocking rules (absolute, or relative to the same directory as the config file)
blocked_names_file = '/etc/CTparental/dnscrypt-blocked-names.txt'
## Optional path to a file logging blocked queries
log_file = '/dev/null'
## Optional log format: tsv or ltsv (default: tsv)
# log_format = 'tsv'
[blocked_ips]
## géré par nftables
[allowed_names]
## Path to the file of allow list rules (absolute, or relative to the same directory as the config file)
allowed_names_file = '/etc/CTparental/dnscrypt-allowed-names.txt'
## Optional path to a file logging allowed queries
# log_file = 'allowed-names.log'
log_file = '/dev/null'
## Optional log format: tsv or ltsv (default: tsv)
# log_format = 'tsv'


